version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: taskflow_db
    restart: always
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
      POSTGRES_DB: taskflowdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: taskflow_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflowdb
      SPRING_DATASOURCE_USERNAME: taskflow
      SPRING_DATASOURCE_PASSWORD: taskflow123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  pgdata:
